
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 12 17:48:24 CET 2023
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 29;
  public static final int DISTINTO = 33;
  public static final int FUNCTION = 24;
  public static final int INT = 13;
  public static final int PUNTOCOMA = 28;
  public static final int OUT = 16;
  public static final int MULTIP = 31;
  public static final int IDENTIFICADOR = 36;
  public static final int IS = 14;
  public static final int AND = 6;
  public static final int RECORD = 19;
  public static final int TYPE = 22;
  public static final int BOOL = 8;
  public static final int BEGIN = 7;
  public static final int NUM = 2;
  public static final int LOOP = 15;
  public static final int IF = 12;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int COMA = 27;
  public static final int CADENA = 3;
  public static final int MENOS = 30;
  public static final int CONSTANT = 9;
  public static final int APERTURA = 25;
  public static final int PUTLINE = 18;
  public static final int MAYOR = 32;
  public static final int DECLARACION = 34;
  public static final int ELSE = 10;
  public static final int PUNTO = 35;
  public static final int WHILE = 23;
  public static final int THEN = 21;
  public static final int END = 11;
  public static final int FALSE = 5;
  public static final int CIERRE = 26;
  public static final int PROCEDURE = 17;
}

